//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto3
//  @ File Name : Consulta.java
//  @ Date : 4/10/2015
//  @ Author : Eduardo Pineda, Javier Gonzalez
//
//

package capaLogica;

import java.sql.Date;
import java.util.ArrayList;


public class Consulta {
	
    private String nombreDoctor;
    private Date fecha;
    private String descripcion;
    private ArrayList<Receta> medicinasRecetadas;
    private ArrayList<Examen> examenesIndicados;
    private String codigoConsulta;
    private ResultadoExamen resultado;
    
    public Consulta(Object pnombreDoctor, Object pfecha, Object pdescripcion) {
    }

    /**
     * @return the codigoConsulta
     */
    public String getCodigoConsulta() {
        return codigoConsulta;
    }

    /**
     * @return the nombreDoctor
     */
    public String getNombreDoctor() {
        return nombreDoctor;
    }

    /**
     * @return the fecha
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * @return the descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @return the medicinasRecetadas
     */
    public ArrayList<Receta> getMedicinasRecetadas() {
        return medicinasRecetadas;
    }

    /**
     * @return the examenesIndicados
     */
    public ArrayList<Examen> getExamenesIndicados() {
        return examenesIndicados;
    }

    /**
     * @return the resultado
     */
    public ResultadoExamen getResultado() {
        return resultado;
    }

    /**
     * @param codigoConsulta the codigoConsulta to set
     */
    private void setCodigoConsulta(String codigoConsulta) {
        this.codigoConsulta = codigoConsulta;
    }

    /**
     * @param nombreDoctor the nombreDoctor to set
     */
    private void setNombreDoctor(String nombreDoctor) {
        this.nombreDoctor = nombreDoctor;
    }

    /**
     * @param fecha the fecha to set
     */
    private void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * @param descripcion the descripcion to set
     */
    private void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @param medicinasRecetadas the medicinasRecetadas to set
     */
    private void setMedicinasRecetadas(ArrayList<Receta> medicinasRecetadas) {
        this.medicinasRecetadas = medicinasRecetadas;
    }

    /**
     * @param examenesIndicados the examenesIndicados to set
     */
    private void setExamenesIndicados(ArrayList<Examen> examenesIndicados) {
        this.examenesIndicados = examenesIndicados;
    }

    /**
     * @param resultado the resultado to set
     */
    private void setResultado(ResultadoExamen resultado) {
        this.resultado = resultado;
    }
}
