//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto3
//  @ File Name : Examen.java
//  @ Date : 4/10/2015
//  @ Author : Eduardo Pineda, Javier Gonzalez
//
//

package capaLogica;

import java.sql.Date;


public class Examen {
    private String nombre;
    private Date fechaSolcitud;
    private String fechaRealizacion;
    private String indicaciones;
    
    public Examen(Object nombre, Object fechaSolicitud, Object fechaRealizacion, Object indicaciones) {
    }

    /**
     * @param nombre the nombre to set
     */
    private void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @param fechaSolcitud the fechaSolcitud to set
     */
    private void setFechaSolcitud(Date fechaSolcitud) {
        this.fechaSolcitud = fechaSolcitud;
    }

    /**
     * @param fechaRealizacion the fechaRealizacion to set
     */
    private void setFechaRealizacion(String fechaRealizacion) {
        this.fechaRealizacion = fechaRealizacion;
    }

    /**
     * @param indicaciones the indicaciones to set
     */
    private void setIndicaciones(String indicaciones) {
        this.indicaciones = indicaciones;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @return the fechaSolcitud
     */
    public Date getFechaSolcitud() {
        return fechaSolcitud;
    }

    /**
     * @return the fechaRealizacion
     */
    public String getFechaRealizacion() {
        return fechaRealizacion;
    }

    /**
     * @return the indicaciones
     */
    public String getIndicaciones() {
        return indicaciones;
    }
}
