//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto3
//  @ File Name : Paciente.java
//  @ Date : 4/10/2015
//  @ Author : Eduardo Pineda, Javier Gonzalez
//
//

package capaLogica;

import java.sql.Date;


public class Paciente {
    private String cedula;
    private String nombre;
    private String direccion;
    private String telefono;
    private Date fechaNacimiento;
    private int edad;
    
    public Paciente(String pcedula, String pnombre, String pdireccion, String ptelefono, Date pfechaNac, int pedad) {
        this.setCedula(pcedula);
        this.setDireccion(pdireccion);
        this.setEdad(pedad);
        this.setFechaNacimiento(pfechaNac);
        this.setNombre(pnombre);
        this.setTelefono(ptelefono);
    }

    /**
     * @return the cedula
     */
    public String getCedula() {
        return cedula;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @return the direccion
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * @return the telefono
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * @return the fechaNacimiento
     */
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * @return the edad
     */
    public int getEdad() {
        return edad;
    }

    /**
     * @param cedula the cedula to set
     */
    private void setCedula(String cedula) {
        this.cedula = cedula;
    }

    /**
     * @param nombre the nombre to set
     */
    private void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @param direccion the direccion to set
     */
    private void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * @param telefono the telefono to set
     */
    private void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * @param fechaNacimiento the fechaNacimiento to set
     */
    private void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    /**
     * @param edad the edad to set
     */
    private void setEdad(int edad) {
        this.edad = edad;
    }
}
