//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto3
//  @ File Name : Receta.java
//  @ Date : 4/10/2015
//  @ Author : Eduardo Pineda, Javier Gonzalez
//
//

package capaLogica;

import java.sql.Date;


public class Receta {
	private int codigoReceta;
    private String dosis;
    private int numeroDias;
    private Date fechaDeInicio;
    private Date fechaFinalizacion;
    private String codigoMedicina;
	private Medicina medicina;
    private int consultaAsociada;
    
    public Receta(int pcodigoReceta, String pdosis, int pnumDias, Date pfechaInicio, Date pfechaFinalizacion, 
    		String pmedicinaAsociada, int pconsultaAsociada) 
    {
    	this.setCodigoReceta(pcodigoReceta);
    	this.setDosis(pdosis);
    	this.setNumeroDias(pnumDias);
    	this.setFechaDeInicio(pfechaInicio);
    	this.setFechaFinalizacion(pfechaFinalizacion);
    	this.setCodigoMedicina(pmedicinaAsociada);
    	this.setConsultaAsociada(pconsultaAsociada);
    }
    
    public String getCodigoMedicina() {
		return codigoMedicina;
	}

	public void setCodigoMedicina(String codigoMedicina) {
		this.codigoMedicina = codigoMedicina;
	}

    private void setCodigoReceta(int codigoReceta) {
		this.codigoReceta = codigoReceta;
	}

	private void setConsultaAsociada(int consultaAsociada) {
		this.consultaAsociada = consultaAsociada;
	}

	public int getCodigoReceta() {
		return codigoReceta;
	}

	public int getConsultaAsociada() {
		return consultaAsociada;
	}

	/**
     * @return the dosis
     */
    public String getDosis() {
        return dosis;
    }

    /**
     * @return the numeroDias
     */
    public int getNumeroDias() {
        return numeroDias;
    }

    /**
     * @return the fechaDeInicio
     */
    public Date getFechaDeInicio() {
        return fechaDeInicio;
    }

    /**
     * @return the fechaFinalizacion
     */
    public Date getFechaFinalizacion() {
        return fechaFinalizacion;
    }

    /**
     * @return the medicina
     */
    public Medicina getMedicina() {
    	if(medicina == null)
    	{
    		medicina = (new MultiMedicina()).buscar(this.getCodigoMedicina());
    	}
        return medicina;
    }
    
    /**
     * @return the nombre medicina
     */
    public String getNombreMedicina() {
    	return this.getMedicina().getNombre();
    }

    /**
     * @param dosis the dosis to set
     */
    private void setDosis(String dosis) {
        this.dosis = dosis;
    }

    /**
     * @param numeroDias the numeroDias to set
     */
    private void setNumeroDias(int numeroDias) {
        this.numeroDias = numeroDias;
    }

    /**
     * @param fechaDeInicio the fechaDeInicio to set
     */
    private void setFechaDeInicio(Date fechaDeInicio) {
        this.fechaDeInicio = fechaDeInicio;
    }

    /**
     * @param fechaFinalizacion the fechaFinalizacion to set
     */
    private void setFechaFinalizacion(Date fechaFinalizacion) {
        this.fechaFinalizacion = fechaFinalizacion;
    }

    
    /**
     * @param medicina the medicina to set
     */
    private void setMedicina(Medicina medicina) {
        this.medicina = medicina;
    }
}
