//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Proyecto3
//  @ File Name : ResultadoExamen.java
//  @ Date : 4/10/2015
//  @ Author : Eduardo Pineda, Javier Gonzalez
//
//

package capaLogica;

import java.util.ArrayList;


public class ResultadoExamen {
    private String codigoResultado;
    private String nombreLugar;
    private String tipoLugar;
    private String descripcionLugar;
    private String examenAsociado;
    private ArrayList<ItemResultado> itemes;
    
    public ResultadoExamen(String codigoResultado, String nombreLugar, String tipoLugar, 
    		String descLugar, String examenAsociado) {
    	
    	this.setCodigoResultado(codigoResultado);
    	this.setDescripcionLugar(examenAsociado);
    	this.setNombreLugar(nombreLugar);
    	this.setTipoLugar(tipoLugar);
    	this.setDescripcionLugar(descLugar);
    }

    public String getExamenAsociado() {
		return examenAsociado;
	}

	public void setExamenAsociado(String examenAsociado) {
		this.examenAsociado = examenAsociado;
	}

	/**
     * @return the codigoResultado
     */
    public String getCodigoResultado() {
        return codigoResultado;
    }

    /**
     * @return the nombreLugar
     */
    public String getNombreLugar() {
        return nombreLugar;
    }

    /**
     * @return the tipoLugar
     */
    public String getTipoLugar() {
        return tipoLugar;
    }

    /**
     * @return the descripcionLugar
     */
    public String getDescripcionLugar() {
        return descripcionLugar;
    }

    /**
     * @return the itemes
     */
    public ArrayList<ItemResultado> getItemes() {
        return itemes;
    }

    /**
     * @param codigoResultado the codigoResultado to set
     */
    private void setCodigoResultado(String codigoResultado) {
        this.codigoResultado = codigoResultado;
    }

    /**
     * @param nombreLugar the nombreLugar to set
     */
    private void setNombreLugar(String nombreLugar) {
        this.nombreLugar = nombreLugar;
    }

    /**
     * @param tipoLugar the tipoLugar to set
     */
    private void setTipoLugar(String tipoLugar) {
        this.tipoLugar = tipoLugar;
    }

    /**
     * @param descripcionLugar the descripcionLugar to set
     */
    private void setDescripcionLugar(String descripcionLugar) {
        this.descripcionLugar = descripcionLugar;
    }

    /**
     * @param itemes the itemes to set
     */
    private void setItemes(ArrayList<ItemResultado> itemes) {
        this.itemes = itemes;
    }
    
    
}
